export enum Events {
    SERVER_RESTART = 'SERVER_RESTART',
    NEW_HOMEPAGE_ACCESS = 'NEW_HOMEPAGE_ACCESS',
    NEW_SANDBOX_EXECUTION = 'NEW_SANDBOX_EXECUTION',
    USER_ACCOUNT_CREATED = 'USER_ACCOUNT_CREATED'
}