apiVersion: v1
kind: Service
metadata:
  name: mfa-api-service
  labels:
    app: mfa
    component: api
spec:
  type: NodePort
  selector:
      app: mfa
      component: api
  ports:
      - port: 5000
        targetPort: 5000
        nodePort: 80
