apiVersion: v1
kind: Service
metadata:
  name: mfa-kafka-service
  labels:
    app: mfa
    component: kafka
spec:
  type: ClusterIP
  selector:
      app: mfa
      component: kafka
  ports:
      - port: 29092
        targetPort: 29092
