apiVersion: v1
kind: Service
metadata:
  name: mfa-zookeeper-service
  labels:
      app: mfa
      component: zookeeper
spec:
  type: ClusterIP
  selector:
      app: mfa
      component: zookeeper
  ports:
      - port: 2181
        targetPort: 2181
