apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfa-api-deployment
  labels:
    app: mfa
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mfa
      component: api
  template:
    metadata:
      labels:
        app: mfa
        component: api
    spec:
      containers:
      - name: web-server
        image: ekyidag/mfa-app:beta
        ports:
        - containerPort: 5000
        command:
          - "npm"
          - "run"
          - "dev:api"
