apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfa-worker-registration-deployment
  labels:
    app: mfa
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mfa
      component: worker-registration
  template:
    metadata:
      labels:
        app: mfa
        component: worker-registration
    spec:
      containers:
      - name: worker-registration
        image: ekyidag/mfa-app:beta
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        command:
          - "npm"
          - "run"
          - "start:worker"
          - "--" 
          - "registration"
