name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      # - name: 'Create env file'
      #   run: ./.github/scripts/create-env.sh
      - name: Install app dependencies
        run: npm ci --legacy-peer-deps
      - name: Setup TERM variable
        run: export TERM
      - name: Run tests
        run: npm run test:ci
      - name: Compile TS into JS
        run: npm run build
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: mfa-ts-app
          path: ./dist
  
  deploy:
    if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: mfa-ts-app
